# [Polynomial Expansion for Orientation and Motion Estimation](http://www.diva-portal.org/smash/get/diva2:302485/FULLTEXT01.pdf)

Gunnar Farnebäck

## 3. Normalized Convolution

## 3.4. Example

In [1]:
import numpy as np

**Marked point**

In [2]:
point = (2, 4)

**Signal**

In [3]:
#                       point x
#                         v
signal = np.array([[3, 7, 4, 5, 8],
                   [9, 2, 4, 4, 6],
                   [5, 1, 4, 3, 7],
                   [3, 1, 1, 2, 8],
                   [4, 6, 2, 3, 6], # < point y
                   [7, 3, 2, 6, 3],
                   [9, 6, 4, 9, 9]])

**Certainty field**

In [4]:
#                         point x
#                            v
certainty = np.array([[0, 2, 2, 2, 2],
                      [2, 1, 1, 2, 2],
                      [2, 1, 1, 2, 1],
                      [2, 2, 2, 2, 1],
                      [1, 0, 2, 2, 2], # < point y
                      [1, 1, 2, 1, 0],
                      [2, 2, 2, 1, 0]])

**Applicability**

In [5]:
applicability = np.array([[1, 2, 1],
                          [2, 4, 2],
                          [1, 2, 1]])

The applicability fixes the size of the neighborhood

In [6]:
size = applicability.shape[0]
half_size = int(size / 2)

**Polynomial basis**

{1, x, y, x², xy, y²}

In [7]:
x, y = np.mgrid[-half_size : half_size + 1, -half_size : half_size + 1].reshape(2, -1)
B = np.stack([np.ones(x.size, dtype=int), x, y, x ** 2, x * y, y ** 2], axis=1)
print(B)

[[ 1 -1 -1  1  1  1]
 [ 1 -1  0  1  0  0]
 [ 1 -1  1  1 -1  1]
 [ 1  0 -1  0  0  1]
 [ 1  0  0  0  0  0]
 [ 1  0  1  0  0  1]
 [ 1  1 -1  1 -1  1]
 [ 1  1  0  1  0  0]
 [ 1  1  1  1  1  1]]


**Applicability as a n x 1 column vector**

In [8]:
a = applicability.T.reshape(-1)
print(a)

[1 2 1 2 4 2 1 2 1]


**Signal neighborhood**

In [9]:
f = signal[point[1] - half_size : point[1] + half_size + 1,
           point[0] - half_size : point[0] + half_size + 1].T.reshape(-1)
print(f)

[1 6 3 1 2 2 2 3 6]


**Certainty neighborhood**

In [10]:
c = certainty[point[1] - half_size : point[1] + half_size + 1,
              point[0] - half_size : point[0] + half_size + 1].T.reshape(-1)
print(c)

[2 0 1 2 2 2 2 2 1]


**Resulting coefficients**

In [11]:
BWaWcB = np.dot(a * c * B.T, B)
print(BWaWcB)

[[26  4 -2 10  0 14]
 [ 4 10  0  4 -2  0]
 [-2  0 14 -2  0 -2]
 [10  4 -2 10  0  6]
 [ 0 -2  0  0  6  0]
 [14  0 -2  6  0 14]]


In [12]:
BWaWcf = np.dot(a * c * B.T, f)
print(BWaWcf)

[55 17  7 27  1 27]


In [13]:
r = np.linalg.inv(BWaWcB).dot(BWaWcf)
print(r)

[ 1.8115942   0.7173913   0.86231884  0.84782609  0.4057971  -0.12318841]


**Reconstructed signal projection**

In [14]:
Br = B.dot(r).reshape(size, size).T
print(Br)

[[1.36231884 0.82608696 1.98550725]
 [1.94202899 1.8115942  3.37681159]
 [2.27536232 2.55072464 4.52173913]]
